---
- name: Create cribl user account.
  user:
    name: "{{ cribl_user }}"
    createhome: true
    home: "/home/{{ cribl_user }}"
    generate_ssh_key: true
    ssh_key_comment: "ansible-{{ inventory_hostname }}"
    groups: "{{ cribl_group }}"
    shell: /sbin/nologin

- name: Fetch the ssh private key
  fetch:
    src: "/home/{{ cribl_user }}/.ssh/id_rsa"
    dest: "~/.ssh/cribl"
    flat: true